import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import IngredientSearch from '../components/IngredientSearch'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Foodstack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <IngredientSearch></IngredientSearch>
     

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
